// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_v4H9y5AxcfwUIPigmRvaCOcQGUd-rRg',
    appId: '1:481476871066:web:caa16ba5e1380da14b3023',
    messagingSenderId: '481476871066',
    projectId: 'themeallab3',
    authDomain: 'themeallab3.firebaseapp.com',
    storageBucket: 'themeallab3.firebasestorage.app',
    measurementId: 'G-13ZZGHD3MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcdCbliAYqfQDtRoUbEO9Zc9bAOiCTNA',
    appId: '1:481476871066:android:be18a7db8b4d1e1b4b3023',
    messagingSenderId: '481476871066',
    projectId: 'themeallab3',
    storageBucket: 'themeallab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb9d1u7-ShEad7miiJ34xaVlNe_635Mbw',
    appId: '1:481476871066:ios:01b253d02d6ebc494b3023',
    messagingSenderId: '481476871066',
    projectId: 'themeallab3',
    storageBucket: 'themeallab3.firebasestorage.app',
    iosBundleId: 'com.example.themeallab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb9d1u7-ShEad7miiJ34xaVlNe_635Mbw',
    appId: '1:481476871066:ios:01b253d02d6ebc494b3023',
    messagingSenderId: '481476871066',
    projectId: 'themeallab3',
    storageBucket: 'themeallab3.firebasestorage.app',
    iosBundleId: 'com.example.themeallab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_v4H9y5AxcfwUIPigmRvaCOcQGUd-rRg',
    appId: '1:481476871066:web:7c68a069e0134eae4b3023',
    messagingSenderId: '481476871066',
    projectId: 'themeallab3',
    authDomain: 'themeallab3.firebaseapp.com',
    storageBucket: 'themeallab3.firebasestorage.app',
    measurementId: 'G-29YHWVG99C',
  );
}
